require: rubocop-custom

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'app/cops/**/*'

# SketchupDeprecations:
#   Enabled: false

# SketchupPerformance:
#   Enabled: false

# SketchupRequirements:
#   Enabled: true

# SketchupSuggestions:
#   Enabled: false
