require: rubocop-sketchup

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'

# SketchupDeprecations:
#   Enabled: false

# SketchupPerformance:
#   Enabled: false

# SketchupRequirements:
#   Enabled: true

# SketchupSuggestions:
#   Enabled: false
