# This rubocop configuration is set up to check the examples folder.

require: rubocop-sketchup

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
    - 'tools/**/*'

# SketchupDeprecations:
#   Enabled: false

# SketchupPerformance:
#   Enabled: false

# SketchupRequirements:
#   Enabled: true

# SketchupSuggestions:
#   Enabled: false
