require:
  - rubocop-performance
  - rubocop-sketchup

inherit_from: sketchup-style.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'examples/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true


# Need to explicitly disable the SketchUp cops here because Rake tasks will
# load the gem and cause them to be run.
# (Not sure why DisabledByDefault isn't enough.)

SketchupBugs:
  Enabled: false

SketchupDeprecations:
  Enabled: false

SketchupPerformance:
  Enabled: false

SketchupRequirements:
  Enabled: false

SketchupSuggestions:
  Enabled: false


Layout/ArrayAlignment:
  Exclude:
    - spec/**/*

Layout/AssignmentIndentation:
  Exclude:
    - tasks/cops_documentation.rake

Layout/FirstArgumentIndentation:
  Exclude:
    - tasks/**/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 80
  Exclude:
    - lib/rubocop/sketchup/cop/suggestions/operation_name.rb
    - spec/**/*
    - tasks/**/*
    - tools/**/*

Layout/IndentationConsistency:
  Exclude:
    - spec/**/*

Layout/ParameterAlignment:
  Exclude:
    - spec/**/*
    - tasks/**/*

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/BooleanSymbol:
  Exclude:
    - lib/rubocop/sketchup/cop/deprecations/operation_next_transparent.rb

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/InterpolationCheck:
  Exclude:
    - spec/rubocop/sketchup/cop/requirements/observers_start_operation_spec.rb

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true


Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - tasks/cops_documentation.rake
    - tasks/cut_release.rake
    - tools/stdlib_scraper.rb

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/ruby_core_namespace.rb
    - lib/rubocop/sketchup/cop/requirements/ruby_stdlib_namespace.rb
    - lib/rubocop/sketchup/formatter/extension_review.rb
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/file_structure.rb
    - lib/rubocop/sketchup/cop/requirements/sketchup_extension.rb
    - tasks/**/*
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - lib/rubocop/sketchup/dc_methods.rb
    - lib/rubocop/sketchup/features.rb


Naming/FileName:
  Exclude:
    - lib/rubocop-sketchup.rb # Not changing the name now.


# When performance isn't critical, computing sizes avoid magic numbers that
# might get out of sync.
Performance/FixedSize:
  Exclude:
    - tasks/cops_documentation.rake

# What this cop suggests makes the code less intuitive/readable.
# Keeping it disabled until there's a known tangible performance impact for this
# gem.
Performance/UnfreezeString:
  Enabled: false


Style/ClassVars:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/extension_namespace.rb
    - lib/rubocop/sketchup/cop/requirements/file_structure.rb

Style/ExponentialNotation:
  Enabled: true

Style/MultilineBlockChain:
  Exclude:
    - lib/rubocop/sketchup/formatter/extension_review.rb

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - spec/**/*
    - tasks/cops_documentation.rake
