require: rubocop-sketchup

inherit_from: sketchup-style.yml

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
    - 'tools/**/*'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true


# Need to explicitly disable the SketchUp cops here because Rake tasks will
# load the gem and cause them to be run.
# (Not sure why DisabledByDefault isn't enough.)

SketchupDeprecations:
  Enabled: false

SketchupPerformance:
  Enabled: false

SketchupRequirements:
  Enabled: false

SketchupSuggestions:
  Enabled: false


Layout/AlignArray:
  Exclude:
    - spec/**/*

Layout/AlignParameters:
  Exclude:
    - spec/**/*

Layout/IndentationConsistency:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - tools/stdlib_scraper.rb

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - tools/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - spec/**/*
